### ISSUE TITLE
Оптимизация шрифтов

### ISSUE THREAD

**Issue by qqpayne** [CyberDAS-Dev/Frontend#105]
Нужно вынести шрифты из `_app` в `_document`, в соответствии с этим руководством: https://nextjs.org/docs/basic-features/font-optimization

**Comment by idonotknowwhoiam** [comment]
Смена _app на _document не добавляет никакой оптимизации, подгружаются только нужные шрифты для текущей страницы. Если у кого-то возникнет вопрос почему не CDN гугла, то при быстром тестировании было выяснено, что селф-хостед шрифты грузятся быстрее.
