### ISSUE TITLE
Оптимизация загрузки изображений

### ISSUE THREAD

**Issue by idonotknowwhoiam** [CyberDAS-Dev/Frontend#18]
Имплементировать лейзи лоад картинок, так-ж прикрутить их автосжатие и их сервинг в зависимости от разрешения экрана пользователя.
Сделать конвертацию в Webp было бы еще лучше.
Так же надо подумать и поработать над кэшированием картинок.

**Comment by qqpayne** [comment]
Задача закрыта, т.к в рамках #100 всё описанное было имплементировано 'за бесплатно'
